import type { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft, ExternalLink, FileText, Github } from "lucide-react"
import { GlyphField } from "@/components/glyph-field"
import { ScrollReveal } from "@/components/scroll-reveal"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Semantic Gravity",
  description:
    "A research program on routing and collapse: content-based routing under a fixed, norm-blind metric, on every axis.",
}

const ARXIV_URL = "https://arxiv.org/abs/2606.22325"
const PAPER_URL = "/publications/all-routes-lead-to-collapse"
const CODE_URL = "https://github.com/parzi-val/all-routes-lead-to-collapse"

type Status = "published" | "shelved" | "active" | "framework" | "blueprint" | "horizon"

const STATUS: Record<Status, { label: string; filled: boolean; muted: boolean }> = {
  published: { label: "published", filled: true, muted: false },
  shelved: { label: "shelved", filled: false, muted: true },
  active: { label: "active", filled: true, muted: false },
  framework: { label: "framework", filled: false, muted: true },
  blueprint: { label: "blueprint", filled: false, muted: true },
  horizon: { label: "horizon", filled: false, muted: true },
}

type LinkRef = { label: string; href: string; icon: "arxiv" | "code" | "page"; internal?: boolean }

type Thread = {
  status: Status
  title: string
  blurb: string
  links?: LinkRef[]
}

const THREADS: Thread[] = [
  {
    status: "published",
    title: "All Routes Lead to Collapse",
    blurb:
      "Paper 1, the diagnosis. Attention sinks, representation collapse, and norm stratification aren't quirks of attention. They're what content-based routing does under a fixed, norm-blind metric, on any axis. Shown across nine transformers and four non-attention routers (graph, state-space, recurrent, depth), with two within-model ablations pinning the cause to the routing itself.",
    links: [
      { label: "Paper", href: PAPER_URL, icon: "page", internal: true },
      { label: "arXiv", href: ARXIV_URL, icon: "arxiv" },
      { label: "Code & data", href: CODE_URL, icon: "code" },
    ],
  },
  {
    status: "shelved",
    title: "The metric fix",
    blurb:
      "The obvious follow-up: restore the magnitude term the metric throws away and see if performance improves. At toy scale it doesn't. A norm-aware score does most of the collapse relief for free, and handing the router more metric freedom is redundant or actively worse. Shelved as a performance play.",
  },
  {
    status: "active",
    title: "Collapse as solution",
    blurb:
      "The reframe that fell out of that null result: maybe collapse isn't the disease but the cure, the model compressing its keys so a flat metric can still tell things apart. The decisive test is an anti-collapse control: regularize the collapse away and watch whether the loss gets worse. The current thread.",
  },
  {
    status: "framework",
    title: "Structural vs emergent concentration",
    blurb:
      "A way to read concentration across architectures: how much is inherited from the substrate (graph hubs, token frequency) versus generated by the routing dynamics. A lens for organizing the cross-architecture results, not a finished theorem.",
  },
  {
    status: "blueprint",
    title: "Hybrid: local attention + global state",
    blurb:
      "A design that eases all four compensation axes at once: a learned-metric local attention beside a global state recurrence, wide heads, and cross-layer access, joined by a slow-waking gate so neither half drowns the other early. On paper for now.",
  },
  {
    status: "horizon",
    title: "Curvature on the token and depth axes",
    blurb:
      "The speculative end: metric curvature on the token axis and learned residuals on the depth axis as two faces of the same geometric enrichment of an otherwise flat network. A possible later paper.",
  },
]

const LOG: { date: string; entry: string }[] = [
  { date: "2026-06-22", entry: "Opened collapse as solution as the active direction." },
  { date: "2026-06-21", entry: "All Routes Lead to Collapse submitted to arXiv." },
  { date: "2026-06", entry: "MIA pilots came back null; the metric-fix intervention was shelved." },
]

const cardClass =
  "rounded-lg border border-border/50 bg-card/55 backdrop-blur-[2px] p-6 transition-colors"

function StatusBadge({ status }: { status: Status }) {
  const s = STATUS[status]
  return (
    <span className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em]">
      <span
        className={cn(
          "h-1.5 w-1.5 rounded-full",
          s.filled ? "bg-foreground" : "border border-muted-foreground/60"
        )}
      />
      <span className={s.muted ? "text-muted-foreground/70" : "text-foreground"}>{s.label}</span>
    </span>
  )
}

export default function SemanticGravityPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground font-sans selection:bg-primary/20">
      {/* the glyph solar system — fixed behind everything on this page */}
      <GlyphField />

      <div className="relative z-10">
        <div className="px-6 pt-8">
          <Link
            href="/"
            className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors group"
          >
            <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
            Back
          </Link>
        </div>

        {/* Hero — field fully visible behind the title */}
        <section className="flex min-h-[78vh] flex-col items-center justify-center px-6 text-center">
          <h1 className="text-4xl md:text-6xl font-medium tracking-tight">Semantic Gravity</h1>
          <p className="mt-5 max-w-xl text-muted-foreground leading-relaxed">
            Content-based routing under a fixed, norm-blind metric produces the same concentration
            signature on every axis.
          </p>
          <p className="mt-8 font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground/70">
            The routes differ; the destination does not.
          </p>
        </section>

        <main className="max-w-3xl mx-auto w-full px-6 pb-32 space-y-20">
          {/* What this is */}
          <ScrollReveal animation="fade-up">
            <p className="text-lg leading-relaxed text-muted-foreground">
              Semantic Gravity is an ongoing program built on one idea: when a model routes
              information by content under a fixed, magnitude-blind similarity metric, it pays for
              the mismatch by concentrating: collapsing its representations onto a low-dimensional
              subspace, leaning on a few anchor tokens, stratifying its norms. The same signature
              turns up whether the routing happens over tokens, nodes, time, or depth. These pages
              track where the idea has gone: what is published, what didn&apos;t pan out, and what
              is still open.
            </p>
          </ScrollReveal>

          {/* Threads */}
          <ScrollReveal animation="fade-up">
            <section className="space-y-6">
              <h2 className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
                Threads
              </h2>
              <div className="space-y-4">
                {THREADS.map((t) => (
                  <article key={t.title} className={cn(cardClass, "hover:border-border")}>
                    <div className="mb-3 flex items-center justify-between gap-4">
                      <h3 className="text-lg font-medium tracking-tight">{t.title}</h3>
                      <StatusBadge status={t.status} />
                    </div>
                    <p className="text-sm leading-relaxed text-muted-foreground">{t.blurb}</p>
                    {t.links && (
                      <div className="mt-4 flex flex-wrap gap-4">
                        {t.links.map((l) => {
                          const linkClass =
                            "inline-flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-foreground transition-colors"
                          const icon =
                            l.icon === "code" ? (
                              <Github className="w-3.5 h-3.5" />
                            ) : l.icon === "page" ? (
                              <FileText className="w-3.5 h-3.5" />
                            ) : (
                              <ExternalLink className="w-3.5 h-3.5" />
                            )
                          return l.internal ? (
                            <Link key={l.label} href={l.href} className={linkClass}>
                              {icon}
                              {l.label}
                            </Link>
                          ) : (
                            <a
                              key={l.label}
                              href={l.href}
                              target="_blank"
                              rel="noopener noreferrer"
                              className={linkClass}
                            >
                              {icon}
                              {l.label}
                            </a>
                          )
                        })}
                      </div>
                    )}
                  </article>
                ))}
              </div>
            </section>
          </ScrollReveal>

          {/* Artifacts */}
          <ScrollReveal animation="fade-up">
            <section className="space-y-4">
              <h2 className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
                Artifacts
              </h2>
              <div className={cn(cardClass, "flex flex-col gap-3")}>
                <a
                  href={ARXIV_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                  <ExternalLink className="w-4 h-4 shrink-0" />
                  arXiv · All Routes Lead to Collapse
                </a>
                <a
                  href={CODE_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors break-all"
                >
                  <Github className="w-4 h-4 shrink-0" />
                  Code &amp; data
                </a>
              </div>
            </section>
          </ScrollReveal>

          {/* Log */}
          <ScrollReveal animation="fade-up">
            <section className="space-y-4">
              <h2 className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
                Log
              </h2>
              <div className={cn(cardClass, "space-y-3")}>
                {LOG.map((l) => (
                  <div key={l.date + l.entry} className="flex gap-4 text-sm">
                    <span className="font-mono text-xs text-muted-foreground/70 shrink-0 w-24 pt-0.5">
                      {l.date}
                    </span>
                    <span className="text-muted-foreground">{l.entry}</span>
                  </div>
                ))}
              </div>
            </section>
          </ScrollReveal>
        </main>
      </div>
    </div>
  )
}
